config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
 end
  
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
    belongs_to :user ## それぞれの投稿は特定１人のユーザーのものとして設定
    validates :user_id, presence: true #user_id が存在すること
    validates :content, presence: true, length: {maximum: 140} #contentがあり、140字以内
    mount_uploader :image, ImageUploader #carrierwaveで追加

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase } #小文字に変換し保存
    validates :name, presence: true, length: {maximum: 50} #空でなく50文字以下指定
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i #mailの正規表現設定
    validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX },  uniqueness: { case_sensitive: false } #空でなく255文字以下、VALID_EMAIL_REGEXと一致他と差別化
    has_secure_password
    has_many :microposts ##それぞれのuserに複数の投稿をもつよう設定
    has_many :following_relationships, class_name: "Relationship",
                                      foreign_key: "follower_id",
                                      dependent: :destroy
    has_many :following_users, through: :following_relationships, source: :followed

    has_many :follower_relationships, class_name: "Relationship",
                                      foreign_key: "followed_id",
                                      dependent: :destroy
    has_many :follower_users, through: :follower_relationships, source: :follower

   # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.create(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationships.find_by(followed_id: other_user.id).destroy
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end

    def feed_items
        Micropost.where(user_id: following_user_ids  + [self.id])
    end
    
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in"
      redirect_to login_url
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create]

    def create
        @micropost = current_user.microposts.build(micropost_params)
        if @micropost.save
            flash[:success] = "Micropost created!"
            redirect_to root_url
        else
            render 'static_pages/home'
        end
    end
    
    def destroy
        @micropost = current_user.microposts.find_by(id: params[:id])
        return redirect_to root_url if @micropost.nil?
        @micropost.destroy
        flash[:success] = "Micropost deleted"
        redirect_to request.referrer || root
    end

    private
    def micropost_params
        params.require(:micropost).permit(:content, :image)
    end
    
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :logged_in_user

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
  end

  def destroy
    @user = current_user.following_relationships.find(params[:id]).followed
    current_user.unfollow(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invaild email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
    @micropost = current_user.microposts.build
    @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
      @user = User.find(params[:id])
      @microposts = @user.microposts
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample app!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(profile_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following_users
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.follower_users
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def profile_params
    params.require(:user).permit(:name, :email, :gender, :country)
  end
  
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user
    end
    
    def store_location
        session[:forwarding_url] = request.url if request.get?
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "Microposts", '#', id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Help", '#' %></li>
                <% if logged_in? %>
                <li><%= link_to "Users", '#' %></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "profile", current_user %></li>
                        <li><%= link_to "settings", "#" %></li>
                        <li class="divider"></li>
                        <li>
                            <%= link_to "log out", logout_path, method: "delete" %>
                        </li>
                    </ul>
                </li>
                <% else %>
                <li><%= link_to "log in", login_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microposts</title>
      <%= stylesheet_link_tag    'application', media: 'all' %>
      <%= javascript_include_tag 'application' %>
      <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %> ">
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
    <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
    <span class="content"><%= micropost.content %></span>
    <% if micropost.image? %>
        <span class="image"><%= link_to image_tag(micropost.image, :size => "250x250"), micropost.image.url %></span>
    <% end %>
    <span class="timestamp">
        posted <%= time_ago_in_words(micropost.created_at) %> ago.
        <% if current_user == micropost.user %>
            <%= link_to "delete", micropost_path(micropost), method: :delete, data: {confirm: "you sure?"} %>
        <% end %>
    </span>
</li>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @user.follower_users.count %>');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.follower_users.count %>');

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation" >
        <div class="alert alert-danger">
          The form contains <%= pluralize(object.errors.count, "error") %>.
        </div>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="microposts">
        <%= render @feed_items %>
    </ol>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
        <%= f.text_area :content, placeholder: "Compose new micropost..." %>
        <%= f.file_field :image %>
    </div>
    <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
    <a href="<%= following_user_path(@user) %>">
        <strong id="following" class="stat">
            <%= @user.following_users.count %>
        </strong>
        following
    </a>
    <a href="<%= followers_user_path(@user) %>">
        <strong id="followers" class="stat">
            <%= @user.follower_users.count %>
        </strong>
        followers
    </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count,"micropost") %></span>

app/views/static_pages/home.html.erb
<% if logged_in? %>
    <div class="row">
        <aside class="col-md-4">
            <section class="user_info">
                <%= render 'shared/user_info' %>
            </section>
            <section>
                <%= render 'shared/stats' %>
            </section>
            <section class="micropost_form">
                <%= render 'shared/micropost_form' %>
            </section>
        </aside>
        <div class="col-md-8">
            <h3>Microposts feed</h3>
            <%= render 'shared/feed' %>
        </div>
    </div>
<% else %>
    <div class="center jumbotron">
        <h1>Welcom to the Microposts</h1>

        <%= link_to "Sign Up now !" , signup_path, class: "btn btn-lg btn-primary" %>
    </div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit</h1>

<div class="row">
    <div class="col-sm-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
        
            <%= f.label :name %>
            <%= f.text_field :name %>
            
            <%= f.label :email %>
            <%= f.text_field :email %>
            
            <%= f.label :gender %>
            <%= f.select :gender, ['male', 'female'] %>
            
            <%= f.label :country %>
            <%= f.text_field :country %>
            
            <%= f.submit "Update User Profile", class: "btn btn-large btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/followers.html.erb
<div class="row">
    <adise class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
        </section>
        <section>
                <%= render 'shared/stats' %>
        </section>
    </adise>
    <div class="col-md-8">
        <%= render 'follow_form' if logged_in? %>
        <% if @users.any? %>
            <h3>Followers (<%= @user.follower_users.count %>)</h3>
            <ol class="followers">
                <% @users.each do |followers| %>
                    <%= link_to gravatar_for(followers, size: 50), user_path(followers.id) %>
                    <%= link_to followers.name, user_path(followers.id) %>
                <br />
                <br />
                <br />
                <% end %>
            </ol>
        <% end %>
    </div>
</div>

app/views/users/following.html.erb
<div class="row">
    <adise class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
        </section>
        <section>
                <%= render 'shared/stats' %>
        </section>
    </adise>
    <div class="col-md-8">
        <%= render 'follow_form' if logged_in? %>
        <% if @users.any? %>
            <h3>Following Users (<%= @user.following_users.count %>)</h3>
                <oi class="followed">
                <% @users.each do |followed| %>
                    <%= link_to gravatar_for(followed, size: 50), user_path(followed) %>
                    <%= link_to followed.name, user_path(followed.id) %>
                    <br />
                    <br />
                    <br />
                    <br />
                <% end %>
                </oi>
        <% end %>
    </div>
</div>

app/views/users/new.html.erb
<h1>SignUp</h1>

<div class="row">
    <div class="col-sm-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
        
            <%= f.label :name %>
            <%= f.text_field :name %>
            
            <%= f.label :email %>
            <%= f.text_field :email %>
            
            <%= f.label :password %>
            <%= f.password_field :password %>
            
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation %>
            
            <%= f.submit "Create My Acocount", class: "btn btn-large btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="row">
    <adise class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
        </section>
        <section>
                <%= render 'shared/stats' %>
        </section>
    </adise>
    <div class="col-md-8">
        <%= render 'follow_form' if logged_in? %>
        <% if @user.microposts.any? %>
            <h3>Microposts (<%= @user.microposts.count %>)</h3>
            <ol class="microposts">
                <%= render @microposts %>
            </ol>
        <% end %>
    </div>
</div>